export const fakeData = [
  {
    firstName: "John",
    lastName: "Doe",
    groupName: "Tech Innovators",
    role: "Software Engineer",
    expectedSalary: 85000,
    expectedDateOfDefense: "2025-06-15",
    id: "1a2b3c4d5e",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    groupName: "AI Pioneers",
    role: "Data Scientist",
    expectedSalary: 95000,
    expectedDateOfDefense: "2025-09-20",
    id: "6f7g8h9i0j",
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    groupName: "Cyber Guardians",
    role: "Security Analyst",
    expectedSalary: 78000,
    expectedDateOfDefense: "2025-12-10",
    id: "k1l2m3n4o5",
  },
  {
    firstName: "Bob",
    lastName: "Williams",
    groupName: "Cloud Experts",
    role: "DevOps Engineer",
    expectedSalary: 90000,
    expectedDateOfDefense: "2025-07-25",
    id: "p6q7r8s9t0",
  },
  {
    firstName: "Emma",
    lastName: "Brown",
    groupName: "Quantum Thinkers",
    role: "Quantum Researcher",
    expectedSalary: 120000,
    expectedDateOfDefense: "2025-05-30",
    id: "u1v2w3x4y5",
  },
];
