export const getFakeData = [
  {
    firstName: "John",
    lastName: "Doe",
    groupName: "Tech Innovators",
    role: "Software Engineer",
    expectedSalary: 85000,
    expectedDateOfDefense: "2025-06-15",
    id: "1a2b3c4d5e",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    groupName: "AI Pioneers",
    role: "Data Scientist",
    expectedSalary: 95000,
    expectedDateOfDefense: "2025-09-20",
    id: "6f7g8h9i0j",
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    groupName: "Cyber Guardians",
    role: "Security Analyst",
    expectedSalary: 78000,
    expectedDateOfDefense: "2025-12-10",
    id: "k1l2m3n4o5",
  },
  {
    firstName: "Bob",
    lastName: "Williams",
    groupName: "Cloud Experts",
    role: "DevOps Engineer",
    expectedSalary: 90000,
    expectedDateOfDefense: "2025-07-25",
    id: "p6q7r8s9t0",
  },
  {
    firstName: "Emma",
    lastName: "Brown",
    groupName: "Quantum Thinkers",
    role: "Quantum Researcher",
    expectedSalary: 120000,
    expectedDateOfDefense: "2025-05-30",
    id: "u1v2w3x4y5",
  },
];

export const putFakeData = [
  {
    firstName: "Zephyr",
    lastName: "Quillsworth",
    groupName: "Quantum Algorithms",
    role: "Lead Researcher",
    expectedSalary: 92000,
    expectedDateOfDefense: "2024-03-22",
    id: "a1b2c3d4-e5f6-7890",
  },
  {
    firstName: "Seraphina",
    lastName: "Montblanc",
    groupName: "Neuroinformatics",
    role: "PhD Candidate",
    expectedSalary: 68000,
    expectedDateOfDefense: "2025-07-14",
    id: "b2c3d4e5-f6g7-8901",
  },
  {
    firstName: "Thaddeus",
    lastName: "Vanderhoff",
    groupName: "Nanophotonics",
    role: "Postdoc Fellow",
    expectedSalary: 78000,
    expectedDateOfDefense: "2023-11-30",
    id: "c3d4e5f6-g7h8-9012",
  },
  {
    firstName: "Isolde",
    lastName: "Ravencroft",
    groupName: "Bio-Robotics",
    role: "Research Engineer",
    expectedSalary: 72000,
    expectedDateOfDefense: "2024-09-05",
    id: "d4e5f6g7-h8i9-0123",
  },
  {
    firstName: "Lysander",
    lastName: "Whitethorne",
    groupName: "Computational Linguistics",
    role: "Doctoral Student",
    expectedSalary: 62000,
    expectedDateOfDefense: "2026-02-18",
    id: "e5f6g7h8-i9j0-1234",
  },
];

export const deleteFakeData = [
  {
    firstName: "Aurelia",
    lastName: "Stormwatch",
    groupName: "Artificial Intelligence",
    role: "Senior Researcher",
    expectedSalary: 95000,
    expectedDateOfDefense: "2025-05-10",
    id: "f1g2h3i4-j5k6-7890",
  },
  {
    firstName: "Cassius",
    lastName: "Moonstone",
    groupName: "Quantum Computing",
    role: "Postdoctoral Fellow",
    expectedSalary: 71000,
    expectedDateOfDefense: "2026-01-20",
    id: "g2h3i4j5-k6l7-8901",
  },
  {
    firstName: "Elysia",
    lastName: "Brightstone",
    groupName: "Robotics Engineering",
    role: "PhD Researcher",
    expectedSalary: 83000,
    expectedDateOfDefense: "2024-12-15",
    id: "h3i4j5k6-l7m8-9012",
  },
  {
    firstName: "Orion",
    lastName: "Blackthorn",
    groupName: "Bioinformatics",
    role: "Project Manager",
    expectedSalary: 76000,
    expectedDateOfDefense: "2025-08-01",
    id: "i4j5k6l7-m8n9-0123",
  },
  {
    firstName: "Callista",
    lastName: "Silverstream",
    groupName: "Data Science",
    role: "Doctoral Candidate",
    expectedSalary: 68000,
    expectedDateOfDefense: "2027-03-22",
    id: "j5k6l7m8-n9o0-1234",
  },
];
